export const USERS_MODULE_DATABASE_INJECT_TOKEN = 'USERS_MODULE_DATABASE';
export const USERS_MODULE_IDENTIFIER_INJECT_TOKEN = 'USERS_MODULE_IDENTIFIER';
export const USERS_MODULE_DATETIME_INJECT_TOKEN = 'USERS_MODULE_DATETIME';
export const USERS_MODULE_LOGGER_INJECT_TOKEN = 'USERS_MODULE_LOGGER';
