export const HTTP_USER_SERVICE_INJECT_TOKEN = 'USER_HTTP_USER_SERVICE';
export const HTTP_EVENT_SERVICE_INJECT_TOKEN = 'USER_HTTP_EVENT_SERVICE';
export const HTTP_DATETIME_INFRA_INJECT_TOKEN = 'USER_HTTP_DATETIME_INFRA';
export const HTTP_LOGGER_INJECT_TOKEN = 'USER_HTTP_LOGGER';
